package gamelagu;

import Lagu.LA1;
import Lagu.LA4;
import Lagu.LN1;
import Lagu.LD1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author windows
 */
public class MenuKategori extends javax.swing.JFrame {


    public MenuKategori() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LaguDaerah = new javax.swing.JButton();
        back = new javax.swing.JButton();
        LaguAnak = new javax.swing.JButton();
        LaguNasional = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LaguDaerah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/daerah1.png"))); // NOI18N
        LaguDaerah.setBorderPainted(false);
        LaguDaerah.setContentAreaFilled(false);
        LaguDaerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaguDaerahActionPerformed(evt);
            }
        });
        getContentPane().add(LaguDaerah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 260, 90));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/back1.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -10, 80, 50));

        LaguAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/anak-anak1.png"))); // NOI18N
        LaguAnak.setBorderPainted(false);
        LaguAnak.setContentAreaFilled(false);
        LaguAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaguAnakActionPerformed(evt);
            }
        });
        getContentPane().add(LaguAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 210, 90));

        LaguNasional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/Nasional.png"))); // NOI18N
        LaguNasional.setContentAreaFilled(false);
        LaguNasional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaguNasionalActionPerformed(evt);
            }
        });
        getContentPane().add(LaguNasional, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 210, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/Interface/Desain icon/kategori.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        setBounds(300, 170, 686, 446);
    }// </editor-fold>//GEN-END:initComponents

    private void LaguDaerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaguDaerahActionPerformed
        new LD1().setVisible(true);
        dispose();
    }//GEN-LAST:event_LaguDaerahActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MenuNama().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void LaguAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaguAnakActionPerformed
        new Lagu.LA1().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_LaguAnakActionPerformed

    private void LaguNasionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaguNasionalActionPerformed
        new LN1().setVisible(true);
        dispose();
    }//GEN-LAST:event_LaguNasionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LaguAnak;
    private javax.swing.JButton LaguDaerah;
    private javax.swing.JButton LaguNasional;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
