package gamelagu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Random;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;

public class MenuNama extends javax.swing.JFrame {

    ResultSet rs = null;
    Statement st;
    Connection conn;
    public static String Nama;
    public static boolean hehe = false;

    /**
     * Creates new form MenuMain
     */
    public MenuNama() {
        initComponents();
//        conn = Koneksi.getKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        Tradisional = new javax.swing.JButton();
        next = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(660, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 160, 40));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/back1.png"))); // NOI18N
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 130, 50));

        Tradisional.setContentAreaFilled(false);
        Tradisional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TradisionalActionPerformed(evt);
            }
        });
        getContentPane().add(Tradisional, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 140, 50));

        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 80, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/Interface/Desain icon/home.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        setBounds(300, 170, 688, 487);
    }// </editor-fold>//GEN-END:initComponents
//public static String Nama2;
    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new MenuAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void TradisionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TradisionalActionPerformed

    }//GEN-LAST:event_TradisionalActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Nama = nama.getText();
        for (int i = 0; i < 5; i++) {
//            if (Nama.equalsIgnoreCase(Main.dbname[i])) {
//                hehe = true;
//                indexScore = i;
//            }
        }
        char name[] = Nama.toCharArray();
        int cek = 0;
        char everything[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '~', '`', '!', '@', '#', '#', '$', '%', '%', '^', '&', '*', '(', ')', '-', '_',
            '+', '=', '[', ']', '{', '}', ':', ';', '"', '?', '/', '.', '>', '<', '|', ' '};
        for (int i = 0; i < name.length; i++) {
            for (int j = 0; j < everything.length; j++) {
                if (name[i] == everything[j]) {
                    cek++;
                }
            }
        }
        if (Nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong", "WARNING", JOptionPane.INFORMATION_MESSAGE);
            nama.requestFocus();
        } else if (Nama.length() > 10) {
            JOptionPane.showMessageDialog(this, "Namanya Terlalu panjang", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else if (Nama.length() < 3) {
            JOptionPane.showMessageDialog(this, "Namanya Terlalu Pendek", "pesan", JOptionPane.WARNING_MESSAGE);
        } else if (cek > 0) {
            JOptionPane.showMessageDialog(this, "Nama Salah", "pesan", JOptionPane.ERROR_MESSAGE);
        } else {
//            JOptionPane.showMessageDialog(this, "Selamat Bermain", "pesan", JOptionPane.INFORMATION_MESSAGE);
            try {
//                theQuery("insert into user (Nama) values('" + nama.getText() + ")");
//                theQuery("INSERT INTO `user` (`ID`, `Nama`) VALUES (NULL, '')");
                theQuery("INSERT INTO `user` (`ID`, `Nama`) VALUES (null,'" + nama.getText() + "' )");
                

            } catch (Exception ex) {

            }

//            cek = 0;
//            Database db = new Database();
//            db.isiTable(nama);
//            new MenuKategori().setVisible(true);
            new MenuKategori().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tradisional;
    private javax.swing.JLabel bg;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables

    public void theQuery(String query) {
        Connection conn = null;
        Statement st = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gamelagu", "root", "");
            st = conn.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Selamat Bermain");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
}
