package gamelagu;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author windows
 */
public class MenuAwal extends javax.swing.JFrame {

    public MenuAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JButton();
        petunjuk = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        tentang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/Main1.png"))); // NOI18N
        main.setBorderPainted(false);
        main.setContentAreaFilled(false);
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 170, 80));

        petunjuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/petunjuk1.png"))); // NOI18N
        petunjuk.setBorderPainted(false);
        petunjuk.setContentAreaFilled(false);
        petunjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petunjukActionPerformed(evt);
            }
        });
        getContentPane().add(petunjuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 160, 80));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/keluar1.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, 80));

        tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/about1.png"))); // NOI18N
        tentang.setBorderPainted(false);
        tentang.setContentAreaFilled(false);
        tentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangActionPerformed(evt);
            }
        });
        getContentPane().add(tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 200, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/Interface/Desain icon/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        setBounds(300, 170, 687, 445);
    }// </editor-fold>//GEN-END:initComponents

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        new MenuNama().setVisible(true);
        dispose();
    }//GEN-LAST:event_mainActionPerformed

    private void tentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangActionPerformed
        new tentang().setVisible(true);
        dispose();
    }//GEN-LAST:event_tentangActionPerformed

    private void petunjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petunjukActionPerformed
        new Petunjuk().setVisible(true);
        dispose();
    }//GEN-LAST:event_petunjukActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JOptionPane pane = new JOptionPane("Apakah kamu ingin Keluar Permainan?");
        Object[] options = new String[]{"Ya", "Tidak ?"};
        pane.setOptions(options);
        JDialog dialog = pane.createDialog(new JFrame(), "Warning !!! ");
        dialog.show();
        Object obj = pane.getValue();
        if (obj.equals("Ya")) {
            System.exit(0);
        } else {
            
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton main;
    private javax.swing.JButton petunjuk;
    private javax.swing.JButton tentang;
    // End of variables declaration//GEN-END:variables
}
